services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages/dto/src:/app/packages/dto/src
    env_file:
      - ./apps/api/.env

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web/src:/app/apps/web/src
      - ./packages/dto/src:/app/packages/dto/src
    environment:
      - API_URL=http://api:3000
    depends_on:
      - api
